# Generated by Django 4.0.5 on 2022-07-04 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_unique-item'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='unique-item',
        ),
    ]
