# Generated by Django 4.0.5 on 2022-06-19 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.brand', verbose_name='Бренд продукта')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.discount', verbose_name='Примененная скидка')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.model', verbose_name='Модель продукта')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.type', verbose_name='Тип продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
