# Generated by Django 4.0.5 on 2022-06-19 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='products.model', verbose_name='Модель продукта'),
        ),
    ]
