# Generated by Django 4.0.5 on 2022-06-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
