# Generated by Django 4.0.5 on 2022-06-20 07:16

from django.db import migrations, models
import django.db.models.deletion
import products.services


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_model_old_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(max_length=256, upload_to=products.services.product_photo_path, verbose_name='Фото продукта')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Фото продукта',
                'verbose_name_plural': 'Фото продуктов',
            },
        ),
    ]
